### ISSUE TITLE
ssh2_connect fatal error

### ISSUE THREAD

**Issue by EmmanuelVella** [BeSimple/BeSimpleDeploymentBundle#4]
You should check if the ssh2_connect function exists, else a PHP fatal error is thrown:  

```
Call to undefined function BeSimple\DeploymentBundle\Deployer\ssh2_connect() in vendor/bundles/BeSimple/DeploymentBundle/Deployer/Ssh.php on line 119
```

**Comment by jfsimon** [comment]
You're right.
Maybe should I implement a Ssh adapter class without ssh2_\* methods?

**Comment by EmmanuelVella** [comment]
Yes, maybe you can directly use ssh via the system, like in the [symfony 1.4 deploy task](http://svn.symfony-project.com/branches/1.4/lib/task/project/sfProjectDeployTask.class.php)
